## **Matrix with NumPy**
A matrix is a rectangular array of numbers, symbols, or expressions arranged in rows and columns. Matrices are used to represent and manipulate data in various fields, including mathematics, physics, computer science, and engineering
<br>**Now lets create matrix using different methods.**

In [2]:
import numpy as np

In [4]:
## Using Fixed Values
mat= np.array([[1,2,3],[4,5,6]])
print('The matrix is:\n',mat)

The matrix is:
 [[1 2 3]
 [4 5 6]]


In [6]:
## Using random values
mat_r= np.random.rand(1,3,3)   #takes values between 0 to 1
print('The random matix is:\n',mat_r)

The random matix is:
 [[[0.3508758  0.77703431 0.44058931]
  [0.62633686 0.51932121 0.20707394]
  [0.99113461 0.4554855  0.04146874]]]


In [8]:
## Matrix of Random Integers
mat_rint= np.random.randint(1,100,(3,3))   #takes values between 1 to 100
print('Matrix of random integers:\n',mat_rint)

Matrix of random integers:
 [[82 65 47]
 [95  1 32]
 [79 18 62]]


In [10]:
## Identity matrix
mat_im= np.eye(3)    # Identity matrix of size 3
print('Identity matrix:\n',mat_im)

Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
## Matrix of zeros and ones
mat_zero= np.zeros((3,3))   # All the elements are zero
mat_one = np.ones((3,3))    # All the elements are one

print(f'Matrix of zeros:\n {mat_zero}\n Matrix of ones:\n {mat_one}')

Matrix of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
 Matrix of ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
# Creating a Diagonal Matrix
diag_mat = np.diag([1, 2, 3])
print('The Diagonal Matrix is:\n',diag_mat)

The Diagonal Matrix is:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]


**Reshaping Flattening**

In [17]:
# Reshaping Matrix 
X=np.random.randint(1,100,(3,4))
re_X= X.reshape(4,3)
print(f'Original matrix of x is:\n {X}\nReshape of matrix X is:{re_X}')

Original matrix of x is:
 [[67 66 88  9]
 [17 98 88 56]
 [78 63 77 41]]
Reshape of matrix X is:[[67 66 88]
 [ 9 17 98]
 [88 56 78]
 [63 77 41]]


In [19]:
# Flattening Matrix X
f_X= X.flatten()
print('Flattened Matrix of X is:\n',f_X)

Flattened Matrix of X is:
 [67 66 88  9 17 98 88 56 78 63 77 41]


**Matrix Stacking**

In [22]:
## Taking two random matrix
A = np.random.randint(1,100,(3,3))
B = np.random.randint(1,100,(3,3))

print(f'Random two matrix are:\n Matrix A:\n{A}\nMatrix:\n{B}')

Random two matrix are:
 Matrix A:
[[43 72  1]
 [40 32 15]
 [79 76 57]]
Matrix:
[[69 92 19]
 [91 83 86]
 [96 48 23]]


In [24]:
## Horizontal Matrix Stacking
hori_A= np.hstack((A,B))
print('Horizontal Stacking of Matrix A:\n',hori_A)

Horizontal Stacking of Matrix A:
 [[43 72  1 69 92 19]
 [40 32 15 91 83 86]
 [79 76 57 96 48 23]]


In [26]:
## Vertical Matrix Stacking
vert_A= np.vstack((A,B))
print('Horizontal Stacking of Matrix A:\n',vert_A)

Horizontal Stacking of Matrix A:
 [[43 72  1]
 [40 32 15]
 [79 76 57]
 [69 92 19]
 [91 83 86]
 [96 48 23]]


**Accessing and Modifying Elements**

In [29]:
#Accessing Elements
ele= A[1,1]     #taking elements from row 2 and column 2
print(f'Original Matrix of A:\n {A}\n Elements at row 2 and column 2: {ele}')

Original Matrix of A:
 [[43 72  1]
 [40 32 15]
 [79 76 57]]
 Elements at row 2 and column 2: 32


In [31]:
#Modifying Elements
print('Original Matrix A:\n',A)
A[1,0]=46   #changing elements at row 2 and 1 as 46
print('Modified Matrix of A:\n', A)

Original Matrix A:
 [[43 72  1]
 [40 32 15]
 [79 76 57]]
Modified Matrix of A:
 [[43 72  1]
 [46 32 15]
 [79 76 57]]


In [33]:
# Accessing Upper Triangular matrix
up_A = np.triu(A)
print('Upper Triangular of Matrix A is:\n',up_A)

Upper Triangular of Matrix A is:
 [[43 72  1]
 [ 0 32 15]
 [ 0  0 57]]


In [35]:
# Accessing Lower Triangular matrix
low_A = np.tril(A)
print('Lower Triangular of Matrix A is:\n',low_A)

Lower Triangular of Matrix A is:
 [[43  0  0]
 [46 32  0]
 [79 76 57]]


In [37]:
## Diagonal Extraction
diag_A= np.diag(A)
print(f'Original Matrix of A:\n {A}\n Diagonal Elements of A is: {diag_A}')

Original Matrix of A:
 [[43 72  1]
 [46 32 15]
 [79 76 57]]
 Diagonal Elements of A is: [43 32 57]


**Matrix Additions and Subtraction**


In [40]:
# Matrix addition 
C= A+B

# Matrix Subtraction 
D= A-B


print(f'After addition the matrix is:\n {C}\n After substraction the matrix is:\n {D}')

After addition the matrix is:
 [[112 164  20]
 [137 115 101]
 [175 124  80]]
 After substraction the matrix is:
 [[-26 -20 -18]
 [-45 -51 -71]
 [-17  28  34]]


**Matrix Multiplication**

In [43]:
# Scaler Multiplication
mult_scal= 2*A
print('Multiplying Matrix A with 2:\n', mult_scal)

Multiplying Matrix A with 2:
 [[ 86 144   2]
 [ 92  64  30]
 [158 152 114]]


In [45]:
# Elementwise Multiplication
mult_ele= A*B
print('Multiplying Matrix A with B:\n', mult_ele)

Multiplying Matrix A with B:
 [[2967 6624   19]
 [4186 2656 1290]
 [7584 3648 1311]]


In [47]:
# Matrix multiplication
mult_mat= A@B
print('Matrix multiplication of A with B:\n', mult_mat)

Matrix multiplication of A with B:
 [[ 9615  9980  7032]
 [ 7526  7608  3971]
 [17839 16312  9348]]


In [49]:
# Dot Multiplication
a=np.array([1,2,3])
b=np.array([6,3,4])
mult_dot=np.dot(a,b)
print('Dot multiplication of A with B:\n', mult_dot)

Dot multiplication of A with B:
 24


In [51]:
# Kronecker Product
c=np.array([[1,2],[3,4]])
d=np.array([[5,2],[6,4]])
k_p = np.kron(a, c)
print('Kronecker Product of Matrix c and d\n',k_p)

Kronecker Product of Matrix c and d
 [[ 1  2  2  4  3  6]
 [ 3  4  6  8  9 12]]


**Transpose Determinant Inverse**

In [54]:
# Transpose of A
trans_A= A.T
print(f'The matrix A is:\n{A}\nTranspose of A is:\n{trans_A}')

The matrix A is:
[[43 72  1]
 [46 32 15]
 [79 76 57]]
Transpose of A is:
[[43 46 79]
 [72 32 76]
 [ 1 15 57]]


In [56]:
# Determinant of A
det_A= np.linalg.det(A)
print('Determinant of A is:\n',det_A)

Determinant of A is:
 -73083.99999999996


In [58]:
# Inverse of A
inv_A= np.linalg.inv(A)
print('Inverse of A is:\n',inv_A)

Inverse of A is:
 [[-0.00935909  0.05511466 -0.01433966]
 [ 0.01966231 -0.0324558   0.00819605]
 [-0.01324503 -0.03311258  0.02649007]]


In [60]:
#Solving liner equation of Ax=a
x=np.linalg.solve(A,a)
print('Solve of liner equation Ax=a\n',x)

Solve of liner equation Ax=a
 [ 5.78512397e-02 -2.06611570e-02 -6.98019338e-19]


**Eigenvalues and Eigenectors**

In [63]:
# Eigenvalues and Eigenectors
e_val,e_vect=np.linalg.eig(A)
print(f'Eigenvalues\n{e_val} \nEigenectors\n{e_vect}')

Eigenvalues
[117.10695579 -18.62126954  33.51431374] 
Eigenectors
[[ 0.341094    0.75312284 -0.30908429]
 [ 0.33889755 -0.64260326  0.02751722]
 [ 0.87681431 -0.14095051  0.95063647]]


**Norms**

In [66]:
norm_A=np.linalg.norm(A)
print('Norms of Matrix A:\n',norm_A)

Norms of Matrix A:
 160.20299622666238


**Rank**

In [69]:
rank = np.linalg.matrix_rank(A)
print('Rank of the matrix A is:', rank)

Rank of the matrix A is: 3


### **Matrix Statistics**

**Mean**

In [73]:
# Mean of Whole Matrix
mean_A= np.mean(A)
print('Mean of Matrix A is : ', mean_A)

Mean of Matrix A is :  46.77777777777778


In [75]:
# Row Mean of a Matrix
mean_A_row=np.mean(A,axis=1)
print('Row mean of Matrix A is:\n',mean_A_row)

Row mean of Matrix A is:
 [38.66666667 31.         70.66666667]


In [77]:
# Column Mean of Matrix
mean_A_col = np.mean(A,axis=0)
print('Column mean of Matrix A is:\n',mean_A_col)

Column mean of Matrix A is:
 [56.         60.         24.33333333]


**Sum**

In [80]:
# Sum of Whole Matrix
t_sum= np.sum(A)
print('Total sum of Matrix A is:',t_sum)

Total sum of Matrix A is: 421


In [82]:
# Row sum of Matrix
r_sum= np.sum(A,axis=1)
print('Row sum of Matrix A is:',r_sum)

Row sum of Matrix A is: [116  93 212]


In [84]:
# Column sum of Matrix
c_sum= np.sum(A,axis=0)
print('Column sum of Matrix A is:',c_sum)

Column sum of Matrix A is: [168 180  73]


**Standard Deviation**

In [87]:
#Whole matrix Standard Deviation
std_A= np.std(A)
print('Whole Matrix Standard Deviation of A is:',std_A)

Whole Matrix Standard Deviation of A is: 25.758613565941516


In [89]:
#Row by Standard Deviation
std_A_r= np.std(A,axis=1)
print('Row by Standard Deviation of A:\n',std_A_r)

Row by Standard Deviation of A:
 [29.14713632 12.67543556  9.7410928 ]


In [99]:
#Column by Standard Deviation
std_A_c= np.std(A,axis=0)
print('Column by Standard Deviation of A:',std_A_c)

Column by Standard Deviation of A: [16.30950643 19.86621923 23.7954244 ]


**Variance**

In [106]:
#Whole matrix Variance 
var_A= np.var(A)
print('Whole Matrix Variance is:',var_A)

Whole Matrix Variance is: 663.5061728395062


In [112]:
#Row wise Variance 
var_A_r= np.var(A,axis=1)
print('Row wise Variance of Matrix A is\n:',var_A_r)

Row wise Variance of Matrix A is
: [849.55555556 160.66666667  94.88888889]


In [116]:
#Column wise Variance 
var_A_c= np.var(A,axis=0)
print('Column wise Variance of Matrix A is\n:',var_A_c)

Column wise Variance of Matrix A is
: [266.         394.66666667 566.22222222]


**Correlation**

In [125]:
#Correlation of Matrix A and B
corr_A_B= np.corrcoef(A,B)
print('Correlation of Matrix A and B is\n:',corr_A_B)

Correlation of Matrix A and B is
: [[ 1.          0.63246716  0.8554686   0.99448629 -0.2714799   0.43404885]
 [ 0.63246716  1.          0.94217939  0.71020833  0.57379475  0.97233897]
 [ 0.8554686   0.94217939  1.          0.90505751  0.26616366  0.83784492]
 [ 0.99448629  0.71020833  0.90505751  1.         -0.16905468  0.52612893]
 [-0.2714799   0.57379475  0.26616366 -0.16905468  1.          0.7492201 ]
 [ 0.43404885  0.97233897  0.83784492  0.52612893  0.7492201   1.        ]]


**Matrix Comparisom**

In [94]:
# Boolean Comparison
com_bool= A>60
print('Comparing each elements of matrix A\n',com_bool)

Comparing each elements of matrix A
 [[False  True False]
 [False False False]
 [ True  True False]]


In [96]:
# Comparing with another matrix
com_mat= A>B
print('Comparing each elements of matrix A with matrix B\n',com_mat)

Comparing each elements of matrix A with matrix B
 [[False False False]
 [False False False]
 [False  True  True]]
